import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { mkdir } from 'node:fs/promises'

test('home opens and core features are navigable', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /A little more in focus/ })).toBeVisible()
  await page.getByRole('button', { name: /Add your first countdown/ }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByLabel('Event title').fill('Trip to the coast')
  await page.getByRole('button', { name: 'Save countdown' }).click()
  await expect(page.getByRole('heading', { name: 'Trip to the coast' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Trip to the coast' })).toBeVisible()
  await page.getByRole('link', { name: /Text tools/ }).click()
  await expect(page.getByRole('heading', { name: 'Text tools' })).toBeVisible()
  await page.getByLabel('Input').fill('one, two')
  await page.getByRole('button', { name: 'CSV to lines' }).click()
  await expect(page.getByLabel('Output')).toHaveValue('one\ntwo')
})

test('first-run home has no serious axe violations', async ({ page }) => {
  await page.goto('/')
  const results = await new AxeBuilder({ page }).analyze()
  expect(results.violations.filter(v => v.impact === 'critical' || v.impact === 'serious').map(v => ({ id: v.id, nodes: v.nodes.length }))).toEqual([])
})

test('mobile navigation exposes every supporting tool', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'More' }).click()
  await expect(page.getByRole('link', { name: /Settings/ })).toBeVisible()
  await page.getByRole('link', { name: /Text tools/ }).click()
  await expect(page.getByRole('heading', { name: 'Text tools' })).toBeVisible()
  for (const width of [1440, 1024, 768, 390]) {
    await page.setViewportSize({ width, height: 844 })
    for (const route of ['#/', '#/meeting', '#/text', '#/qr']) {
      await page.goto(`/${route}`)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `No horizontal overflow at ${width}px on ${route}`).toBe(true)
    }
  }
})

test('portable single-file opens without a server', async ({ page }) => {
  const fileUrl = `file:///${process.cwd().replaceAll('\\', '/')}/dist-portable/OfficeDesk.html`
  await page.goto(fileUrl)
  await expect(page.getByRole('heading', { name: /A little more in focus/ })).toBeVisible()
  await page.getByRole('button', { name: /Dates/ }).click()
  await expect(page.getByRole('heading', { name: 'Date calculator' })).toBeVisible()
  await page.getByRole('link', { name: /Quick note/ }).click()
  await page.getByLabel('Quick note').fill('Offline note from file mode')
  await page.reload()
  await expect(page.getByLabel('Quick note')).toHaveValue('Offline note from file mode')
})

test('hosted shell reloads offline after first cache', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  await page.reload()
  await page.waitForFunction(() => Boolean(navigator.serviceWorker?.controller), null, { timeout: 15_000 })
  await page.context().setOffline(true)
  try {
    await page.reload()
    await expect(page.getByRole('heading', { name: /A little more in focus/ })).toBeVisible()
  } finally {
    await page.context().setOffline(false)
  }
})

test('meeting clock reaches overtime and announces the state', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00') })
  await page.goto('/#/meeting')
  await page.getByLabel('Minutes').fill('1')
  await page.getByRole('button', { name: /Start/ }).click()
  await page.clock.fastForward(61_000)
  await expect(page.locator('.timer-digits small')).toHaveText('OVERTIME')
  await expect(page.locator('.timer-digits span')).toContainText('+00:00:01')
})

test('share link reconstructs only the chosen countdown', async ({ page, context, browser }) => {
  if (browser.browserType().name() === 'firefox') {
    await page.addInitScript(() => { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async (value: string) => localStorage.setItem('e2e.clipboard', value), readText: async () => localStorage.getItem('e2e.clipboard') ?? '' } }) })
  } else await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/')
  await page.getByRole('button', { name: /Add your first countdown/ }).click()
  await page.getByLabel('Event title').fill('Coastal week')
  await page.getByLabel('Subtitle').fill('A few days away')
  await page.getByRole('button', { name: 'Save countdown' }).click()
  await page.getByRole('link', { name: /Countdowns/ }).click()
  await page.getByRole('button', { name: 'Share' }).click()
  const shareUrl = await page.evaluate(() => navigator.clipboard.readText())
  expect(shareUrl).toContain('#/share=')
  const recipientContext=await browser.newContext()
  const recipient=await recipientContext.newPage()
  await recipient.goto(shareUrl)
  await expect(recipient.getByRole('heading', { name: 'Coastal week' })).toBeVisible()
  await recipient.getByRole('button', { name: 'Save to My Countdowns' }).click()
  await expect(recipient.getByRole('article').getByRole('heading', { name: 'Coastal week' })).toBeVisible()
  await recipientContext.close()
})

test('countdowns can be promoted, edited, duplicated, and deleted', async ({ page }) => {
  await page.goto('/#/countdown')
  await page.getByRole('button', { name: /New countdown/ }).click()
  await page.getByLabel('Event title').fill('Quarterly launch')
  await page.getByRole('button', { name: 'Save countdown' }).click()
  await page.getByRole('button', { name: /New countdown/ }).click()
  await page.getByLabel('Event title').fill('Quarterly close')
  await page.getByRole('button', { name: 'Save countdown' }).click()
  const event = page.getByRole('article').filter({ hasText: 'Quarterly close' })
  await event.getByRole('button', { name: /Make primary/ }).click()
  await expect(event.getByText('PRIMARY', { exact: true })).toBeVisible()
  await event.getByRole('button', { name: 'Edit' }).click()
  await page.getByLabel('Event title').fill('Quarterly launch revised')
  await page.getByRole('button', { name: 'Save countdown' }).click()
  const revised = page.getByRole('article').filter({ hasText: 'Quarterly launch revised' })
  await revised.getByRole('button', { name: 'Duplicate' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Save countdown' }).click()
  await expect(page.getByRole('article')).toHaveCount(3)
  page.on('dialog', dialog => dialog.accept())
  await page.getByRole('article').last().getByRole('button', { name: 'Delete' }).click()
  await expect(page.getByRole('article')).toHaveCount(2)
  await page.getByRole('article').filter({ hasText: 'Quarterly launch revised' }).getByRole('button', { name: 'Delete' }).click()
  await expect(page.getByRole('article')).toHaveCount(1)
  await expect(page.getByRole('article').getByText('PRIMARY', { exact: true })).toBeVisible()
})

test('saved countdown changes synchronize across tabs', async ({ page, context }) => {
  const secondTab = await context.newPage()
  await Promise.all([page.goto('/'), secondTab.goto('/')])
  await page.getByRole('button', { name: /Add your first countdown/ }).click()
  await page.getByLabel('Event title').fill('Shared between tabs')
  await page.getByRole('button', { name: 'Save countdown' }).click()
  await expect(secondTab.getByRole('heading', { name: 'Shared between tabs' })).toBeVisible()
  await secondTab.close()
})

test('app remains usable when browser storage is blocked', async ({ page }) => {
  await page.addInitScript(() => { Object.defineProperty(window, 'localStorage', { configurable: true, get: () => { throw new DOMException('Storage is blocked', 'SecurityError') } }) })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: /A little more in focus/ })).toBeVisible()
  await expect(page.getByRole('status')).toHaveText('Storage is full or unavailable. Your latest changes may not persist.')
})

test('custom countdown images reject vector payloads without uploading them', async ({ page }) => {
  await page.goto('/#/countdown')
  await page.getByRole('button', { name: /New countdown/ }).click()
  await page.locator('input[type="file"]').setInputFiles({ name: 'remote.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"/>') })
  await expect(page.getByRole('status')).toHaveText('Choose a PNG, JPEG, WebP, or GIF image.')
  await expect(page.getByText('Preparing image…')).toHaveCount(0)
})

test('countdown editor is accessible and traps keyboard focus', async ({ page }) => {
  await page.goto('/#/countdown')
  const opener = page.getByRole('button', { name: /New countdown/ })
  await opener.click()
  const dialog = page.getByRole('dialog')
  const results = await new AxeBuilder({ page }).analyze()
  expect(results.violations.filter(v => v.impact === 'critical' || v.impact === 'serious').map(v => v.id)).toEqual([])
  await page.getByRole('button', { name: 'Save countdown' }).focus()
  await expect(page.getByRole('button', { name: 'Save countdown' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: 'Close' })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'Save countdown' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(opener).toBeFocused()
  await page.goto('/#/settings')
  await page.getByRole('combobox').selectOption('dark')
  const darkResults = await new AxeBuilder({ page }).analyze()
  expect(darkResults.violations.filter(v => v.impact === 'critical' || v.impact === 'serious').map(v => v.id)).toEqual([])
})

test('checklist, business calculations, and QR generation work end to end', async ({ page }) => {
  await page.goto('/#/notes')
  await page.getByRole('button', { name: /Checklist/ }).click()
  await page.getByLabel('New checklist item').fill('Send the agenda')
  await page.getByRole('button', { name: /Add/ }).click()
  await expect(page.getByLabel('Checklist item 1')).toHaveValue('Send the agenda')
  await page.getByRole('button', { name: 'Mark complete' }).click()
  await expect(page.getByRole('button', { name: 'Mark incomplete' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: /Checklist/ }).click()
  await expect(page.getByRole('button', { name: 'Mark incomplete' })).toBeVisible()

  await page.goto('/#/dates')
  await page.getByLabel('Start date').fill('2026-09-24')
  await page.getByLabel('End date').fill('2026-09-28')
  await expect(page.getByText('business days (Mon–Fri)', { exact: true })).toBeVisible()
  await expect(page.locator('.date-results div').nth(2).locator('strong')).toHaveText('2')

  await page.goto('/#/text')
  await page.getByLabel('Input').fill('b\na\nb')
  await page.getByRole('button', { name: 'Remove duplicate lines' }).click()
  await expect(page.getByLabel('Output')).toHaveValue('b\na')
  await page.getByRole('button', { name: 'UPPERCASE' }).click()
  await expect(page.getByLabel('Output')).toHaveValue('B\nA\nB')

  await page.goto('/#/percent')
  await expect(page.getByRole('heading', { name: 'Percentage calculator' })).toBeVisible()
  const percentOfNumber = page.locator('.percent-grid .tool-panel').filter({ hasText: 'Find a percentage of a number' })
  await percentOfNumber.getByLabel('Percent (%)').fill('15')
  await percentOfNumber.getByLabel('Whole number').fill('200')
  await expect(percentOfNumber.locator('.calc-result')).toHaveText('30%')
  const percentChange = page.locator('.percent-grid .tool-panel').filter({ hasText: 'Percent change' })
  await percentChange.getByLabel('Starting value').fill('80')
  await percentChange.getByLabel('Ending value').fill('100')
  await expect(percentChange.locator('.calc-result')).toHaveText('25%')
  const margin = page.locator('.percent-grid .tool-panel').filter({ hasText: 'PROFIT MARGIN' })
  const markup = page.locator('.percent-grid .tool-panel').filter({ hasText: 'MARKUP ON COST' })
  await margin.getByLabel('Selling price (amount charged)').fill('100')
  await margin.getByLabel('Cost (your expense)').fill('80')
  await markup.getByLabel('Selling price (amount charged)').fill('100')
  await markup.getByLabel('Cost (your expense)').fill('80')
  await expect(margin.locator('.calc-result')).toHaveText('20%')
  await expect(markup.locator('.calc-result')).toHaveText('25%')

  await page.goto('/#/qr')
  await page.getByLabel('Text or URL').fill('https://example.com/office')
  await page.getByRole('button', { name: 'Generate code' }).click()
  await expect(page.getByRole('img', { name: 'Generated QR code' })).toHaveAttribute('src', /^data:image\/png/)
})

test('timer completion and focus-to-break transition use the selected durations', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00') })
  await page.goto('/#/timer')
  await page.getByLabel('Minutes').fill('1')
  await page.getByRole('button', { name: /Start/ }).click()
  await page.clock.fastForward(60_000)
  await expect(page.locator('.timer-digits small')).toHaveText('TIME')

  await page.goto('/#/focus')
  await page.getByLabel('Focus minutes').fill('1')
  await page.getByRole('button', { name: /Start focus/ }).click()
  await page.clock.fastForward(60_000)
  await expect(page.locator('.phase-label')).toHaveText('TAKE A BREATH')
  await expect(page.locator('.focus-digits')).toHaveText('05:00')
})

test('timer start uses current time after the page has been idle', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00') })
  await page.goto('/#/timer')
  await expect(page.locator('.timer-digits span')).toHaveText('25:00')
  await page.clock.fastForward(5 * 60_000)
  await expect(page.locator('.timer-digits span')).toHaveText('25:00')
  await page.getByRole('button', { name: /Start/ }).click()
  await expect(page.locator('.timer-digits span')).toHaveText('25:00')
})

test('timer pause holds remaining time and resume continues from that value', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-09-24T12:00:00') })
  await page.goto('/#/timer')
  await page.getByRole('button', { name: /Start/ }).click()
  await page.clock.fastForward(30_000)
  await page.getByRole('button', { name: /Pause/ }).click()
  const paused = await page.locator('.timer-digits span').textContent()
  await page.clock.fastForward(60_000)
  await expect(page.locator('.timer-digits span')).toHaveText(paused!)
  await page.getByRole('button', { name: /Start/ }).click()
  const resumed = await page.locator('.timer-digits span').textContent()
  await page.clock.fastForward(10_000)
  const afterResume = await page.locator('.timer-digits span').textContent()
  const asSeconds = (value: string) => { const [minutes, seconds] = value.split(':').map(Number); return minutes * 60 + seconds }
  expect(asSeconds(resumed!)-asSeconds(afterResume!)).toBeGreaterThanOrEqual(9)
  expect(asSeconds(resumed!)-asSeconds(afterResume!)).toBeLessThanOrEqual(11)
})

test('captures representative desktop, mobile, theme, and tool screens', async ({ page }) => {
  await mkdir('docs/screenshots', { recursive: true })
  await page.clock.install({ time: new Date() })
  await page.setViewportSize({ width: 1440, height: 1050 })
  await page.goto('/')
  await page.screenshot({ path: 'docs/screenshots/home-desktop.png', fullPage: true })
  await page.getByRole('button', { name: /Add your first countdown/ }).click()
  await page.getByLabel('Event title').fill('Mountain weekend')
  const futureLocalMinute = await page.evaluate(() => { const d=new Date(Date.now()+120_000);d.setSeconds(0,0);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}` })
  await page.getByLabel('Target date and time').fill(futureLocalMinute)
  await page.getByRole('dialog').getByRole('combobox').nth(3).selectOption('party')
  await page.getByRole('button', { name: 'Save countdown' }).click()
  const heroDigitColor = await page.locator('.hero .time-unit strong').first().evaluate(element => getComputedStyle(element).color)
  expect(heroDigitColor).toBe('rgb(245, 245, 238)')
  await page.screenshot({ path: 'docs/screenshots/countdown-vacation-desktop.png', fullPage: true })
  await page.clock.fastForward(130_000)
  await expect(page.getByRole('dialog', { name: /Mountain weekend is here/ })).toBeVisible()
  await expect(page.locator('.party-confetti')).toBeVisible()
  const completionColor = await page.locator('.hero .complete-label').evaluate(element => getComputedStyle(element).color)
  expect(completionColor).toBe('rgb(255, 255, 255)')
  await page.screenshot({ path: 'docs/screenshots/party-completion.png', fullPage: true })
  await page.getByRole('button', { name: 'Dismiss' }).click()
  await page.evaluate(() => localStorage.clear())
  await page.reload()
  await page.goto('/#/')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'docs/screenshots/home-mobile.png' })
  await page.getByRole('link', { name: /Countdowns/ }).click()
  await page.getByRole('button', { name: /New countdown/ }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'docs/screenshots/countdown-editor-mobile.png', fullPage: true })
  await page.locator('.modal').evaluate(element=>element.scrollTop=element.scrollHeight)
  await page.screenshot({ path: 'docs/screenshots/countdown-editor-mobile-bottom.png', fullPage: true })
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: /Close/ }).waitFor({ state: 'detached' })
  await page.goto('/#/settings')
  await page.getByRole('combobox').selectOption('dark')
  await page.screenshot({ path: 'docs/screenshots/dark-mode-mobile.png', fullPage: true })
  await page.goto('/#/text')
  await page.screenshot({ path: 'docs/screenshots/text-tools-mobile.png', fullPage: true })
  await page.goto('/#/meeting')
  await page.getByLabel('Minutes').fill('1')
  await page.getByRole('button', { name: /Start/ }).click()
  await page.clock.fastForward(61_000)
  await page.screenshot({ path: 'docs/screenshots/meeting-overtime.png', fullPage: true })
})
